-- Priority 2 migration: mutasi barang, serah terima, histori log, dan dokumen transaksi

CREATE TABLE IF NOT EXISTS mutasi_barang (
  id INT NOT NULL AUTO_INCREMENT,
  kode_mutasi VARCHAR(60) NOT NULL,
  tanggal_mutasi DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  gudang_asal_id INT NOT NULL,
  gudang_tujuan_id INT NOT NULL,
  jenis_barang ENUM('asset','consumable','campuran') NOT NULL DEFAULT 'campuran',
  catatan TEXT NULL,
  dokumen_file VARCHAR(255) NULL,
  status ENUM('draft','disetujui','selesai','dibatalkan') NOT NULL DEFAULT 'draft',
  created_by INT NULL,
  created_by_name VARCHAR(255) NOT NULL,
  approved_by INT NULL,
  approved_by_name VARCHAR(255) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_mutasi_barang_kode (kode_mutasi),
  KEY idx_mutasi_barang_tanggal (tanggal_mutasi),
  KEY idx_mutasi_barang_gudang_asal (gudang_asal_id),
  KEY idx_mutasi_barang_gudang_tujuan (gudang_tujuan_id),
  KEY idx_mutasi_barang_status (status),
  KEY idx_mutasi_barang_created_by (created_by),
  KEY idx_mutasi_barang_approved_by (approved_by),
  CONSTRAINT fk_mutasi_barang_gudang_asal FOREIGN KEY (gudang_asal_id) REFERENCES gudang(id_gudang) ON DELETE RESTRICT,
  CONSTRAINT fk_mutasi_barang_gudang_tujuan FOREIGN KEY (gudang_tujuan_id) REFERENCES gudang(id_gudang) ON DELETE RESTRICT,
  CONSTRAINT fk_mutasi_barang_created_by FOREIGN KEY (created_by) REFERENCES user(id_user) ON DELETE SET NULL,
  CONSTRAINT fk_mutasi_barang_approved_by FOREIGN KEY (approved_by) REFERENCES user(id_user) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS mutasi_barang_detail (
  id INT NOT NULL AUTO_INCREMENT,
  mutasi_id INT NOT NULL,
  produk_id INT NOT NULL,
  unit_barang_id INT NULL,
  qty INT NOT NULL DEFAULT 1,
  satuan_snapshot VARCHAR(50) NULL,
  kondisi_sebelum VARCHAR(50) NULL,
  kondisi_sesudah VARCHAR(50) NULL,
  catatan_detail TEXT NULL,
  PRIMARY KEY (id),
  KEY idx_mutasi_barang_detail_mutasi (mutasi_id),
  KEY idx_mutasi_barang_detail_produk (produk_id),
  KEY idx_mutasi_barang_detail_unit (unit_barang_id),
  CONSTRAINT fk_mutasi_barang_detail_mutasi FOREIGN KEY (mutasi_id) REFERENCES mutasi_barang(id) ON DELETE CASCADE,
  CONSTRAINT fk_mutasi_barang_detail_produk FOREIGN KEY (produk_id) REFERENCES produk(id_produk) ON DELETE RESTRICT,
  CONSTRAINT fk_mutasi_barang_detail_unit FOREIGN KEY (unit_barang_id) REFERENCES unit_barang(id_unit_barang) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS serah_terima_barang (
  id INT NOT NULL AUTO_INCREMENT,
  kode_serah_terima VARCHAR(60) NOT NULL,
  tanggal_serah_terima DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  jenis_tujuan ENUM('user','lokasi','departemen') NOT NULL DEFAULT 'user',
  pihak_penyerah_user_id INT NULL,
  pihak_penyerah_nama VARCHAR(255) NOT NULL,
  pihak_penerima_user_id INT NULL,
  pihak_penerima_nama VARCHAR(255) NOT NULL,
  gudang_asal_id INT NULL,
  lokasi_tujuan VARCHAR(255) NULL,
  catatan TEXT NULL,
  dokumen_file VARCHAR(255) NULL,
  status ENUM('aktif','dikembalikan','dibatalkan') NOT NULL DEFAULT 'aktif',
  created_by INT NULL,
  created_by_name VARCHAR(255) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_serah_terima_barang_kode (kode_serah_terima),
  KEY idx_serah_terima_tanggal (tanggal_serah_terima),
  KEY idx_serah_terima_status (status),
  KEY idx_serah_terima_gudang_asal (gudang_asal_id),
  KEY idx_serah_terima_penyerah (pihak_penyerah_user_id),
  KEY idx_serah_terima_penerima (pihak_penerima_user_id),
  KEY idx_serah_terima_created_by (created_by),
  CONSTRAINT fk_serah_terima_barang_gudang_asal FOREIGN KEY (gudang_asal_id) REFERENCES gudang(id_gudang) ON DELETE SET NULL,
  CONSTRAINT fk_serah_terima_barang_penyerah FOREIGN KEY (pihak_penyerah_user_id) REFERENCES user(id_user) ON DELETE SET NULL,
  CONSTRAINT fk_serah_terima_barang_penerima FOREIGN KEY (pihak_penerima_user_id) REFERENCES user(id_user) ON DELETE SET NULL,
  CONSTRAINT fk_serah_terima_barang_created_by FOREIGN KEY (created_by) REFERENCES user(id_user) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS serah_terima_detail (
  id INT NOT NULL AUTO_INCREMENT,
  serah_terima_id INT NOT NULL,
  produk_id INT NOT NULL,
  unit_barang_id INT NULL,
  qty INT NOT NULL DEFAULT 1,
  kondisi_serah VARCHAR(50) NOT NULL DEFAULT 'baik',
  kondisi_kembali VARCHAR(50) NULL,
  tanggal_kembali DATETIME NULL,
  catatan_detail TEXT NULL,
  PRIMARY KEY (id),
  KEY idx_serah_terima_detail_header (serah_terima_id),
  KEY idx_serah_terima_detail_produk (produk_id),
  KEY idx_serah_terima_detail_unit (unit_barang_id),
  CONSTRAINT fk_serah_terima_detail_header FOREIGN KEY (serah_terima_id) REFERENCES serah_terima_barang(id) ON DELETE CASCADE,
  CONSTRAINT fk_serah_terima_detail_produk FOREIGN KEY (produk_id) REFERENCES produk(id_produk) ON DELETE RESTRICT,
  CONSTRAINT fk_serah_terima_detail_unit FOREIGN KEY (unit_barang_id) REFERENCES unit_barang(id_unit_barang) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS histori_log (
  id INT NOT NULL AUTO_INCREMENT,
  ref_type ENUM('mutasi','handover','barang_masuk','barang_keluar','tracking','unit') NOT NULL,
  ref_id INT NOT NULL,
  event_type VARCHAR(100) NOT NULL,
  produk_id INT NULL,
  unit_barang_id INT NULL,
  gudang_id INT NULL,
  user_id INT NULL,
  user_name_snapshot VARCHAR(255) NOT NULL,
  target_user_id INT NULL,
  target_user_name_snapshot VARCHAR(255) NULL,
  deskripsi TEXT NULL,
  meta_json LONGTEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_histori_log_ref (ref_type, ref_id),
  KEY idx_histori_log_produk (produk_id),
  KEY idx_histori_log_unit (unit_barang_id),
  KEY idx_histori_log_gudang (gudang_id),
  KEY idx_histori_log_user (user_id),
  KEY idx_histori_log_target_user (target_user_id),
  KEY idx_histori_log_created_at (created_at),
  CONSTRAINT fk_histori_log_produk FOREIGN KEY (produk_id) REFERENCES produk(id_produk) ON DELETE SET NULL,
  CONSTRAINT fk_histori_log_unit FOREIGN KEY (unit_barang_id) REFERENCES unit_barang(id_unit_barang) ON DELETE SET NULL,
  CONSTRAINT fk_histori_log_gudang FOREIGN KEY (gudang_id) REFERENCES gudang(id_gudang) ON DELETE SET NULL,
  CONSTRAINT fk_histori_log_user FOREIGN KEY (user_id) REFERENCES user(id_user) ON DELETE SET NULL,
  CONSTRAINT fk_histori_log_target_user FOREIGN KEY (target_user_id) REFERENCES user(id_user) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS dokumen_transaksi (
  id INT NOT NULL AUTO_INCREMENT,
  ref_type ENUM('mutasi','handover','barang_masuk','barang_keluar') NOT NULL,
  ref_id INT NOT NULL,
  jenis_dokumen VARCHAR(100) NOT NULL DEFAULT 'lampiran',
  file_path VARCHAR(255) NOT NULL,
  uploaded_by INT NULL,
  uploaded_by_name VARCHAR(255) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_dokumen_transaksi_ref (ref_type, ref_id),
  KEY idx_dokumen_transaksi_uploaded_by (uploaded_by),
  CONSTRAINT fk_dokumen_transaksi_uploaded_by FOREIGN KEY (uploaded_by) REFERENCES user(id_user) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
