ALTER TABLE user
  ADD COLUMN IF NOT EXISTS deleted_at DATETIME NULL AFTER created_at;

ALTER TABLE user
  ADD COLUMN IF NOT EXISTS updated_at DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER deleted_at;
